-- Royal Library — Supabase schema
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  role text not null default 'member' check (role in ('member','admin')),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  isbn text,
  category_id bigint references public.categories(id) on delete set null,
  description text,
  keywords text,
  cover_url text,
  published_year integer,
  total_copies integer not null default 1 check (total_copies >= 0),
  available_copies integer not null default 1 check (available_copies >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.borrowings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  borrowed_at timestamptz not null default now(),
  due_at timestamptz not null default (now() + interval '14 days'),
  returned_at timestamptz,
  status text not null default 'borrowed' check (status in ('borrowed','returned','overdue')),
  created_at timestamptz not null default now()
);

create table if not exists public.favourites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, book_id)
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  book_id bigint references public.books(id) on delete cascade,
  activity_type text not null check (activity_type in ('view','search','borrow','return','favourite')),
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_books_category on public.books(category_id);
create index if not exists idx_books_title on public.books using gin (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(author,'') || ' ' || coalesce(description,'') || ' ' || coalesce(keywords,'')));
create index if not exists idx_borrowings_user on public.borrowings(user_id);
create index if not exists idx_borrowings_book on public.borrowings(book_id);
create index if not exists idx_activities_user on public.activities(user_id);

insert into public.categories(name, description) values
('Computer Science','Programming, software engineering, systems and computing.'),
('Business','Entrepreneurship, management and business strategy.'),
('Literature','Novels, poetry, drama and literary works.'),
('Science','Natural sciences, mathematics and scientific thinking.'),
('History','Historical works and world history.'),
('Self Development','Personal growth, habits and productivity.'),
('Education','Learning, teaching and academic resources.'),
('Technology','Emerging technology, AI and digital innovation.')
on conflict (name) do nothing;

-- Create profile automatically after signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email,''),'@',1)),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Borrowing transaction with inventory protection.
create or replace function public.borrow_book(p_book_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.books
  set available_copies = available_copies - 1,
      updated_at = now()
  where id = p_book_id and available_copies > 0;

  if not found then
    raise exception 'Book is not available';
  end if;

  insert into public.borrowings(user_id, book_id)
  values (auth.uid(), p_book_id)
  returning id into new_id;

  insert into public.activities(user_id, book_id, activity_type)
  values (auth.uid(), p_book_id, 'borrow');

  return jsonb_build_object('id', new_id);
end;
$$;

create or replace function public.return_book(p_borrowing_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_book_id bigint;
begin
  update public.borrowings
  set returned_at = now(), status = 'returned'
  where id = p_borrowing_id
    and user_id = auth.uid()
    and returned_at is null
  returning book_id into v_book_id;

  if not found then
    raise exception 'Borrowing record not found';
  end if;

  update public.books
  set available_copies = least(total_copies, available_copies + 1),
      updated_at = now()
  where id = v_book_id;

  insert into public.activities(user_id, book_id, activity_type)
  values (auth.uid(), v_book_id, 'return');

  return true;
end;
$$;

-- Lightweight hybrid recommendation RPC.
-- Content signal: matching category/author/keywords with the user's previous books.
-- Collaborative signal: books borrowed by users who also borrowed the current user's books.
create or replace function public.get_recommendations(p_limit integer default 8)
returns table (
  id bigint,
  title text,
  author text,
  category text,
  description text,
  cover_url text,
  score numeric
)
language sql
stable
security definer
set search_path = public
as $$
with my_books as (
  select distinct b.id, b.category_id, lower(coalesce(b.author,'')) author, lower(coalesce(b.keywords,'')) keywords
  from public.borrowings br
  join public.books b on b.id = br.book_id
  where br.user_id = auth.uid()
),
similar_users as (
  select distinct br2.user_id
  from public.borrowings br1
  join public.borrowings br2 on br1.book_id = br2.book_id
  where br1.user_id = auth.uid()
    and br2.user_id <> auth.uid()
),
candidates as (
  select
    b.*,
    (
      case when exists(select 1 from my_books m where m.category_id = b.category_id) then 3 else 0 end +
      case when exists(select 1 from my_books m where m.author <> '' and lower(b.author) = m.author) then 2 else 0 end +
      case when exists(
        select 1 from my_books m
        where m.keywords <> '' and lower(coalesce(b.keywords,'')) like '%' || split_part(m.keywords, ',', 1) || '%'
      ) then 1 else 0 end +
      case when exists(
        select 1 from public.borrowings br
        where br.user_id in (select user_id from similar_users)
          and br.book_id = b.id
      ) then 2 else 0 end
    )::numeric as score
  from public.books b
  where not exists (
    select 1 from public.borrowings br where br.user_id = auth.uid() and br.book_id = b.id and br.returned_at is null
  )
)
select c.id, c.title, c.author, cat.name, c.description, c.cover_url, c.score
from candidates c
left join public.categories cat on cat.id = c.category_id
order by c.score desc, c.created_at desc
limit greatest(1, least(p_limit, 50));
$$;

-- Starter catalogue

-- Explicit Data API grants. RLS policies below remain the authorization boundary.
grant usage on schema public to anon, authenticated;

grant select on public.categories to anon, authenticated;
grant select on public.books to anon, authenticated;

grant select, update on public.profiles to authenticated;
grant select on public.borrowings to authenticated;
grant select, insert, delete on public.favourites to authenticated;
grant select, insert on public.activities to authenticated;
grant select on public.notifications to authenticated;

grant insert, update, delete on public.books to authenticated;
grant insert, update, delete on public.categories to authenticated;
grant insert, update, delete on public.borrowings to authenticated;


-- RLS
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.books enable row level security;
alter table public.borrowings enable row level security;
alter table public.favourites enable row level security;
alter table public.activities enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "public categories read" on public.categories;
create policy "public categories read" on public.categories for select using (true);

drop policy if exists "public books read" on public.books;
create policy "public books read" on public.books for select using (true);

drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read" on public.profiles for select using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update" on public.profiles for update using (auth.uid() = id or public.is_admin());

drop policy if exists "admins manage books" on public.books;
create policy "admins manage books" on public.books for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "borrowings self read" on public.borrowings;
create policy "borrowings self read" on public.borrowings for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "admins borrowings all" on public.borrowings;
create policy "admins borrowings all" on public.borrowings for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "favourites self all" on public.favourites;
create policy "favourites self all" on public.favourites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "activities self insert" on public.activities;
create policy "activities self insert" on public.activities for insert with check (auth.uid() = user_id);

drop policy if exists "activities self read" on public.activities;
create policy "activities self read" on public.activities for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "notifications self" on public.notifications;
create policy "notifications self" on public.notifications for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant execute on function public.borrow_book(bigint) to authenticated;
grant execute on function public.return_book(bigint) to authenticated;
grant execute on function public.get_recommendations(integer) to authenticated;
grant execute on function public.is_admin() to authenticated;
